# Generated by Django 4.0.4 on 2022-06-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=63)),
                ('Text', models.CharField(max_length=255)),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
    ]
